# Generated by Django 4.2 on 2024-01-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FizzBuzz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fizzbuzz_id", models.IntegerField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("useragent", models.CharField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
    ]
