# Generated by Django 4.2 on 2024-01-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fizzbuzz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fizzbuzz",
            name="fizzbuzz_id",
            field=models.CharField(max_length=36),
        ),
    ]
